Devise導入、モデル、コントローラーの生成
kiindmanjio/chat-space pull request #5
Opened 2017-02-18 07:55 UTC by kiindmanjio

1.素材のダウンロード
2.deviseの導入
3.deviseのビューファイルの追加
4.サインアップ機能の追加
5.サインイン / サインアウト機能の追加
6.ユーザー情報編集機能の追加

2017-02-18 08:00 UTC, kiindmanjio commented
## 質問

`attr_accessor :name`が記述されているとnameカラムsign_up,account_updateの時にカラムに保存されないのはなぜか？
[screen shot 2017-02-18 at 4 57 50 pm](https://cloud.githubusercontent.com/assets/21217051/23091521/78b8c570-f5fb-11e6-8525-eb4ec20040c9.png)

2017-02-18 08:13 UTC, hc0208 requested changes

2017-02-18 08:13 UTC, hc070208 commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
&__innerみたいな書き方してほしいな
他の部分も

2017-02-18 08:13 UTC, hc070208 commented on app/models/user.rb
> +    validates :name, presence: true
インデントあわせよう

2017-02-18 08:13 UTC, hc070208 commented on app/views/devise/confirmations/new.html.erb
> +<%= render "devise/shared/links" %>
全部hamlにしよう

2017-02-18 14:26 UTC, kiindmanjio commented
>&__innerみたいな書き方してほしいな
他の部分も

scssの書き方を変えてもあたらないです。。
ビューの方も書き方は変えますか？

2017-02-18 14:35 UTC, hc070208 commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
これがまだかな

2017-02-18 14:36 UTC, hc070208 commented
書き方かえなくてもいけるはずなんだけどなー
他のやつで試してみて！

2017-02-19 03:42 UTC, hc070208 commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
ここがまだか笑

2017-02-19 03:55 UTC, hc070208 commented
LGTM

2017-02-19 04:01 UTC, merged